### ISSUE TITLE
[1.2.1] Can't find the configuration file config\theabyss2.json

### ISSUE THREAD

**Issue by Fzoss** [Harve/GoCreateModpack#4]
This error occurs frequently on the server and causes the server to crash.

[21:57:48] [Server thread/INFO] [login_shield/]: Teleporting player: TextComponent{text='', siblings=[TextComponent{text='894MUI', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell 894MUI '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.util.text.event.HoverEvent$EntityHover@606dc234'}, insertion=894MUI, font=minecraft:default}}
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]: java.io.FileNotFoundException: config\theabyss2.json (系统找不到指定的文件。)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at java.io.FileInputStream.open0(Native Method)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at java.io.FileInputStream.open(Unknown Source)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at java.io.FileInputStream.<init>(Unknown Source)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at java.io.FileReader.<init>(Unknown Source)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.yezon.theabyss.procedures.ReadConfigFileProcedure.executeProcedure(ReadConfigFileProcedure.java:49)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.yezon.theabyss.procedures.ReadConfigFileProcedure$GlobalTrigger.onPlayerLoggedIn(ReadConfigFileProcedure.java:36)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraftforge.eventbus.ASMEventHandler_1455_GlobalTrigger_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:231)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[21:57:48] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:86]:         at java.lang.Thread.run(Unknown Source)
[21:57:49] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 14
        Listeners:
                0: HIGHEST
                1: ASM: class owmii.losttrinkets.item.trinkets.RubyHeartTrinket saveHealthTickStart(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                2: HIGH
                3: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                4: NORMAL
                5: ASM: class com.connectivity.event.EventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                6: ASM: com.github.alexthe666.citadel.server.CitadelEvents@7d23e296 onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                7: ASM: class com.feed_the_beast.mods.ftbessentials.FTBEEventHandler serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                8: ASM: class owmii.lib.util.Server tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                9: ASM: class com.endertech.minecraft.forge.network.MotionController onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                10: ASM: class com.mrh0.buildersaddition.event.GameEvents tickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                11: ASM: class com.black_dog20.servertabinfo.common.events.ServerEvents onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                12: ASM: net.minecraftforge.common.ForgeInternalHandler@312f006c onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                13: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                14: ASM: ca.glasspelican.loginshield.LoginShield@73bb7fe7 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                15: ASM: class com.simibubi.create.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                16: ASM: journeymap.server.events.ForgeEvents@31d150ed onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
        at java.util.LinkedList$ListItr.next(Unknown Source)
        at ca.glasspelican.loginshield.LoginShield.onServerTick(LoginShield.java:70)
        at net.minecraftforge.eventbus.ASMEventHandler_658_LoginShield_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:785)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Unknown Source)

[21:57:49] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source) ~[?:1.8.0_291] {}
        at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:1.8.0_291] {}
        at ca.glasspelican.loginshield.LoginShield.onServerTick(LoginShield.java:70) ~[login_shield:1.16.5-5-g909ffa8] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_658_LoginShield_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:115) ~[forge:?] {re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:785) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

**Comment by Fzoss** [comment]
I probably fixed the problem.

[The Abyss: Chapter II](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii) 
`
CONFIG FILE

SINGLEPLAYER: use /ta2cc to create a config file. (it will create in your config folder)
MULTIPLAYER: use /ta2cc or ta2cc in the server console. (it will create in your config folder)
`

![image](https://user-images.githubusercontent.com/20693292/125302406-7c7e1200-e35e-11eb-8d17-88139fe7c703.png)

**Comment by Harve** [comment]
The Abyss mod usually doesn't need the config to run (and shouldn't without it crash as far as I know). The crash log also mentions the Login Shield mod. Let me know what happens when the crash occurs, or if creating the config fixes the crash.

**Comment by Fzoss** [comment]
> The Abyss mod usually doesn't need the config to run (and shouldn't without it crash as far as I know). The crash log also mentions the Login Shield mod. Let me know what happens when the crash occurs, or if creating the config fixes the crash.

Since it's a server environment with players (10 or more), it's hard to determine what they did before the crash, but based on feedback, it's probably easier to trigger when teleporting across worlds or when players log in.
In the last 48 hours there have been about 10 crashes due to this problem, and the last error before the crash was due to this config not being found.
At least after the config was generated, there were no more crashes caused by this issue.

**Comment by Harve** [comment]
I will provide the config in all server versions going forward in order to prevent this issue for anyone else.
